### ISSUE TITLE
Fail to run the jar or Main.java

### ISSUE THREAD

**Issue by Symbolk** [ualberta-smr/RefactoringsInMergeCommits#2]
Hi there! I have been trying to run the project, both as jar and in Intellij IDEA. However, I got into some troubles.

1. After successfully building the jar with maven, but when I execute the following commands in git bash, it tells me the following error message:
```sh
$ java -jar refactoring-analysis.jar -h
Error: Could not find or load main class ca.ualberta.cs.smr.refactoring.analysis.Main
$ java -cp .;./refactoring-analysis.jar ca.ualberta.cs.smr.refactoring.analysis.Main -h
./refactoring-analysis.jar: line 1: $'PK\003\004': command not found
./refactoring-analysis.jar: line 2: KYVN: command not found
./refactoring-analysis.jar: line 3:JYVN▒▒i?META-INF/MANIFEST.MFE▒▒: No such file or directory
./refactoring-analysis.jar: line 10: syntax error near unexpected token `('
./refactoring-analysis.jar: line 10: !^▒3▒▒2L8nt_tasks/resources-ant.jar
```
2. I tried to build and run the project source code Main.java in Intellij IDEA, but the following error message is given:
```sh
java.util.concurrent.ExecutionException: org.javalite.activejdbc.InitException: org.javalite.activejdbc.InitException: failed to determine Model class name, are you sure models have been instrumented?
```
After some investigation, I think it is a problem with the IDE and the activejdbc:

https://stackoverflow.com/questions/43282524/debugging-activejdbc-with-intellij-idea
https://github.com/javalite/activejdbc/issues/654

Any suggestion to help me out? Thanks!

**Comment by mehrmoudi** [comment]
I'm sorry to hear that, I'll look intro fixing the Maven problem over the weekend. In the meantime, I can help you with the Intellij IDEA problem.

You need to run the ActiveJDBC instrumentation Maven plugin. To do that, find this plugin on the Maven Project tab in Intellij, under plugins. This video explains this in more details.
https://youtu.be/OHXJXzZNKCU?t=63

**Comment by mehrmoudi** [comment]
I found a fix to the Maven problem as well, it was very minor. Use this command instead:
```
./mvnw clean activejdbc-instrumentation:instrument compile assembly:single clean
```
I've updated the main README file to reflect this as well. Please let me know if this fixes it.
Thank you for reporting this!

**Comment by Symbolk** [comment]
> I found a fix to the Maven problem as well, it was very minor. Use this command instead:
> 
> ```
> ./mvnw clean activejdbc-instrumentation:instrument compile assembly:single clean
> ```
> I've updated the main README file to reflect this as well. Please let me know if this fixes it.
> Thank you for reporting this!

Great, this do fix the problem.
